type Company {
    id: ID!
    symbol: String!
    name: String!
    sector: String!
    industry: String!
    description: String
    logoUrl: String
    exchange: String!
}

type Quote {
    currentPrice: Float!
    high: Float!
    low: Float!
    open: Float!
    previousClose: Float!
    timestamp: Int!
}

type Candle {
    datetime: String!
    open: Float!
    high: Float!
    low: Float!
    close: Float!
    volume: Float!
}

type StockDetail {
    company: Company!
    quote: Quote!
    candles: [Candle!]!
}

type Query {
    companies: [Company!]!
    company(symbol: String!): Company
    stockDetail(symbol: String!, interval: String = "1day", outputSize: Int = 30): StockDetail
}
