'use client'

import { useResearchNotes } from '@/hooks/useResearchNotes'

const TIPS = [
  'Enter a ticker in AI Research to kick off an autonomous multi-step research run.',
  'Use Compare to line up fundamentals and relative performance across a few stocks.',
  'Every completed AI run is saved to Notes automatically for later reading.',
]

export default function ResearchWorkspaceRail({ onOpenNotes }: { onOpenNotes: () => void }) {
  const { data: notes, isPending } = useResearchNotes()
  const recentNotes = (notes ?? []).slice(0, 4)

  return (
    <aside className="sticky top-24 flex flex-col gap-4">
      <section className="rounded-lg border border-[var(--color-border)] bg-[var(--color-card-bg)] p-4">
        <div className="mb-3 flex items-center justify-between">
          <h2 className="text-sm font-semibold text-[var(--color-text-primary)]">Recent notes</h2>
          <button
            type="button"
            onClick={onOpenNotes}
            className="text-xs font-medium text-[var(--color-accent-blue)] hover:underline"
          >
            View all
          </button>
        </div>

        {isPending && (
          <div className="flex flex-col gap-2">
            {Array.from({ length: 3 }).map((_, i) => (
              <div
                key={i}
                className="h-12 animate-pulse rounded-md bg-[var(--color-sidebar-hover)]"
              />
            ))}
          </div>
        )}

        {!isPending && recentNotes.length === 0 && (
          <p className="text-xs text-[var(--color-text-secondary)]">
            Notes generated by the AI agent will show up here.
          </p>
        )}

        {!isPending && recentNotes.length > 0 && (
          <ul className="flex flex-col gap-1">
            {recentNotes.map((note) => (
              <li key={note.id}>
                <button
                  type="button"
                  onClick={onOpenNotes}
                  className="flex w-full flex-col items-start rounded-md p-2 text-left transition-colors hover:bg-[var(--color-sidebar-hover)]"
                >
                  <span className="text-xs font-medium text-[var(--color-text-primary)]">
                    {note.company.symbol}
                  </span>
                  <span className="line-clamp-1 text-xs text-[var(--color-text-secondary)]">
                    {note.title}
                  </span>
                </button>
              </li>
            ))}
          </ul>
        )}
      </section>

      <section className="rounded-lg border border-[var(--color-border)] bg-[var(--color-card-bg)] p-4">
        <h2 className="mb-3 text-sm font-semibold text-[var(--color-text-primary)]">
          Workspace tips
        </h2>
        <ul className="flex flex-col gap-3">
          {TIPS.map((tip) => (
            <li key={tip} className="flex gap-2 text-xs text-[var(--color-text-secondary)]">
              <span className="mt-1 h-1 w-1 shrink-0 rounded-full bg-[var(--color-accent-blue)]" />
              {tip}
            </li>
          ))}
        </ul>
      </section>
    </aside>
  )
}
