'use client'

import { useState } from 'react'
import Link from 'next/link'
import { useResearchNotes } from '@/hooks/useResearchNotes'
import ChatMarkdown from '@/components/chat/ChatMarkdown'
import CompanyLogo from '@/components/companies/CompanyLogo'

function NotesSkeleton() {
  return (
    <div className="flex flex-col gap-6 sm:flex-row">
      <div className="flex w-full shrink-0 flex-col gap-2 sm:max-w-xs">
        {Array.from({ length: 5 }).map((_, i) => (
          <div
            key={i}
            className="flex flex-col gap-2 rounded-lg border border-[var(--color-border)] p-3"
          >
            <div className="h-3 w-16 animate-pulse rounded bg-[var(--color-sidebar-hover)]" />
            <div className="h-3 w-32 animate-pulse rounded bg-[var(--color-sidebar-hover)]" />
          </div>
        ))}
      </div>
      <div className="hidden flex-1 flex-col gap-3 sm:flex">
        <div className="h-6 w-64 animate-pulse rounded bg-[var(--color-sidebar-hover)]" />
        <div className="h-4 w-full animate-pulse rounded bg-[var(--color-sidebar-hover)]" />
        <div className="h-4 w-5/6 animate-pulse rounded bg-[var(--color-sidebar-hover)]" />
        <div className="h-4 w-3/4 animate-pulse rounded bg-[var(--color-sidebar-hover)]" />
      </div>
    </div>
  )
}

function NotesError({ onRetry }: { onRetry: () => void }) {
  return (
    <div className="flex flex-col items-center justify-center gap-3 rounded-lg border border-dashed border-[var(--color-loss)]/40 bg-red-50/40 py-16 text-center">
      <p className="font-medium text-[var(--color-text-primary)]">Couldn&apos;t load notes</p>
      <p className="text-sm text-[var(--color-text-secondary)]">
        Something went wrong. Please try again.
      </p>
      <button
        type="button"
        onClick={onRetry}
        className="rounded-md bg-[var(--color-accent-blue)] px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-blue-700"
      >
        Retry
      </button>
    </div>
  )
}

export default function ResearchNotesTab() {
  const { data: notes, isPending, isError, refetch } = useResearchNotes()
  const [selectedNoteId, setSelectedNoteId] = useState<string | null>(null)

  const visibleNotes = notes ?? []
  const selectedNote = visibleNotes.find((n) => n.id === selectedNoteId)

  return (
    <div className="flex flex-col gap-6">
      {isPending && <NotesSkeleton />}
      {isError && !isPending && <NotesError onRetry={() => void refetch()} />}

      {notes && !isPending && !isError && (
        <div className="flex flex-col gap-6 sm:flex-row">
          {/* Sidebar: note list */}
          <div className="flex w-full shrink-0 flex-col gap-2 overflow-y-auto sm:max-w-xs sm:max-h-[65vh] sm:border-r sm:border-[var(--color-border)] sm:pr-4">
            {visibleNotes.length === 0 ? (
              <div className="flex flex-col items-center gap-1 rounded-lg border border-dashed border-[var(--color-border)] py-12 text-center">
                <p className="text-sm font-medium text-[var(--color-text-primary)]">
                  No notes saved yet
                </p>
                <p className="text-xs text-[var(--color-text-secondary)]">
                  Research notes generated by the AI agent will show up here.
                </p>
              </div>
            ) : (
              visibleNotes.map((note) => (
                <button
                  key={note.id}
                  type="button"
                  onClick={() => setSelectedNoteId(note.id)}
                  className={`flex items-start gap-3 rounded-lg border p-3 text-left transition-colors ${
                    selectedNoteId === note.id
                      ? 'border-[var(--color-accent-blue)] bg-[var(--color-accent-light)]'
                      : 'border-[var(--color-border)] hover:bg-[var(--color-sidebar-hover)]'
                  }`}
                >
                  <CompanyLogo symbol={note.company.symbol} logoUrl={note.company.logoUrl} />
                  <div className="flex min-w-0 flex-1 flex-col items-start">
                    <div className="flex w-full items-center justify-between gap-2">
                      <span className="font-medium text-[var(--color-text-primary)]">
                        {note.company.symbol}
                      </span>
                      <span className="shrink-0 text-xs text-[var(--color-text-secondary)]">
                        {new Date(note.createdAt).toLocaleDateString()}
                      </span>
                    </div>
                    <h3 className="mt-1 line-clamp-1 text-sm text-[var(--color-text-secondary)]">
                      {note.title}
                    </h3>
                    <span className="mt-2 rounded-full bg-[var(--color-sidebar-hover)] px-2 py-0.5 text-[10px] font-medium tracking-wide text-[var(--color-text-secondary)] uppercase">
                      By {note.generatedBy}
                    </span>
                  </div>
                </button>
              ))
            )}
          </div>

          {/* Main content: note reader */}
          <div className="flex-1 overflow-y-auto sm:max-h-[65vh]">
            {selectedNote ? (
              <article className="pb-4">
                <div className="mb-6 flex items-start gap-3 border-b border-[var(--color-border)] pb-4">
                  <CompanyLogo
                    symbol={selectedNote.company.symbol}
                    logoUrl={selectedNote.company.logoUrl}
                  />
                  <div className="min-w-0">
                    <h2 className="mb-2 text-xl font-semibold text-[var(--color-text-primary)]">
                      {selectedNote.title}
                    </h2>
                    <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-sm text-[var(--color-text-secondary)]">
                      <Link
                        href={`/stocks/${selectedNote.company.symbol}`}
                        className="font-medium text-[var(--color-accent-blue)] hover:underline"
                      >
                        {selectedNote.company.symbol} · {selectedNote.company.name}
                      </Link>
                      <span aria-hidden>•</span>
                      <span>{new Date(selectedNote.createdAt).toLocaleString()}</span>
                    </div>
                  </div>
                </div>

                <div className="text-sm text-[var(--color-text-primary)]">
                  <ChatMarkdown content={selectedNote.content} />
                </div>
              </article>
            ) : (
              <div className="flex h-full min-h-[240px] flex-col items-center justify-center gap-1 rounded-lg border border-dashed border-[var(--color-border)] text-center">
                <p className="text-sm font-medium text-[var(--color-text-primary)]">
                  Select a note to read
                </p>
                <p className="text-xs text-[var(--color-text-secondary)]">
                  Pick a research note from the list on the left.
                </p>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}
